Feature/no proxy
adriansmares/lnd pull request #2
Opened 2021-08-22 03:28 UTC by 3nprob

#### Pull Request Checklist

- [x] If this is your first time contributing, we recommend you read the [Code
  Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
- [x] All changes are Go version 1.12 compliant
- [x] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
- [ ] For new code: Code is accompanied by tests which exercise both
  the positive and negative (error paths) conditions (if applicable)
- [ ] For bug fixes: Code is accompanied by new tests which trigger
  the bug being fixed to prevent regressions
- [x] Any new logging statements use an appropriate subsystem and
  logging level
- [x] Code has been formatted with `go fmt`
- [x] Protobuf files (`lnrpc/**/*.proto`) have been formatted with
  `make rpc-format` and compiled with `make rpc`
- [x] New configuration flags have been added to `sample-lnd.conf`
- [x] For code and documentation: lines are wrapped at 80 characters
  (the tab character should be counted as 8 characters, not 4, as some IDEs do
  per default)
- [x] Running `make check` does not fail any tests
- [ ] Running `go vet` does not report any issues
- [ ] Running `make lint` does not report any **new** issues that did not
  already exist
- [x] All commits build properly and pass tests. Only in exceptional
  cases it can be justifiable to violate this condition. In that case, the
  reason should be stated in the commit message.
- [x] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)

2021-08-22 12:33 UTC, Kixunil requested changes
Disclaimer: I only did light review and didn't perform thorough check of logic.

Note that despite me disagreeing with the change **as-is**, I'm fine with the general idea and want to express my appreciation for you actually doing the work for a feature you want. :)

2021-08-22 12:33 UTC, Kixunil commented on config.go
> +	NoProxyTargets    string        `long:"no-proxy-targets" description:"Comma-separated values specifying hosts that should bypass the clearnet proxy. Each value is either an IP address, a CIDR range,
From my experience ignoring parsing/validation errors is one of the worst things you can do to yourself as a developer. Such things are complete nightmare to debug and nearly impossible to communicate from user to the developer. It can also easily become a source of security vulnerabilities. (Not sure in this case.)

I strongly recommend and, as a user and a small contributor to LND, ask to adopt exactly opposite strategy: anything ambiguous or unexpected to be treated as hard error and reported loudly.

2021-08-22 12:33 UTC, Kixunil commented on lnd.go
> +		srvrLog.Warn("!!! Skipping Tor while Stream Isolation is on." +
If you really want to enable this please add an explicit switch to do so. At the current state when someone gets the warning it's already too late.

2021-08-23 02:36 UTC, 3nprob commented on config.go
> +	NoProxyTargets    string        `long:"no-proxy-targets" description:"Comma-separated values specifying hosts that should bypass the clearnet proxy. Each value is either an IP address, a CIDR range,
I tend to somwhat agree in principle. However:

1. I don't see how much more explicit you can be than `skip-proxy-for-clearnet-targets=true`
2. Doing stream isolation for onions while using e.g. I2P or some other obfuscated proxy for clearnet (maybe even a separate tor gateway that has stream isolation configured on the tor side)  is really not that exotic or even close to invalid

Open for  suggestions if you have anything concrete in mind to make this work without making it overly convoluted tho!

2021-08-23 03:03 UTC, 3nprob commented on config.go
> +	NoProxyTargets    string        `long:"no-proxy-targets" description:"Comma-separated values specifying hosts that should bypass the clearnet proxy. Each value is either an IP address, a CIDR range,
I might add... Existing default behavior (lnd attempting to connect over tors SOCKS proxy for connections to `localhost` and rfc1878 networks) is a similar footgun that could yield compromise if the tor node is misconfigured or compromised - if anything, I'd  say that's a more practical risk if you at some point make assumptions tat these networks are trusted

2021-08-23 03:06 UTC, 3nprob commented
@Kixunil Thanks for checking in, I'm closing this in favor of https://github.com/lightningnetwork/lnd/pull/5651 in the main repo as https://github.com/lightningnetwork/lnd/pull/5410 was merged now

2021-08-23 03:48 UTC, closed without merging

2021-08-23 09:27 UTC, Kixunil commented on config.go
> +	NoProxyTargets    string        `long:"no-proxy-targets" description:"Comma-separated values specifying hosts that should bypass the clearnet proxy. Each value is either an IP address, a CIDR range,
Let's say one mistypes `127.0.0.1` as `327.0.0.1`. Ignoring it will cause the filter to never hit and lead to confusing connection problems.

Regarding stream isolation + skip proxy: it's not invalid but confusing. You want both security and not security? Probably a mistake. Maybe a safe way to not fail is to ignore `skip-proxy-for-clearnet-targets` and print a warning - that way at least privacy is not lost accidentally.

2021-08-23 09:43 UTC, 3nprob commented on config.go
> +	NoProxyTargets    string        `long:"no-proxy-targets" description:"Comma-separated values specifying hosts that should bypass the clearnet proxy. Each value is either an IP address, a CIDR range,
Well, I may want LND to do its stream isolation for the tor proxy used for onion addresses, while the proxy itself used for clearnet connections is responsible for securing clearnet connections. Nothing wild with that.

2021-08-23 09:48 UTC, Kixunil commented on config.go
> +	NoProxyTargets    string        `long:"no-proxy-targets" description:"Comma-separated values specifying hosts that should bypass the clearnet proxy. Each value is either an IP address, a CIDR range,
Ah, I see. Maybe a `i-have-a-special-secure-setup` switch for these kinds of things. :D